FROM node:20-alpine

WORKDIR /usr/src/app

# Install PostgreSQL client tools for pg_isready
RUN apk add postgresql-client

# Enable corepack, this allow using pnpm
RUN corepack enable

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install all dependencies for development
RUN pnpm install

# Copy the dev entrypoint script into the container
COPY entrypoint.dev.sh .

# Make the dev entrypoint script executable
RUN chmod +x entrypoint.dev.sh

# Expose the port for the development server
EXPOSE 5473

# The entrypoint will be used as the command
ENTRYPOINT ["./entrypoint.dev.sh"]